import type { EntityStyle, NamedColors, Theme } from './shape.js';

// Named-color mapping for grayscale theme. Each named color maps to a
// distinct grey by lightness so `bg:blue` etc. remain differentiable
// in black-and-white print without relying on automatic colour conversion.
export const grayscaleNamed: NamedColors = {
    red: '#4a4a4a',
    blue: '#6b6b6b',
    green: '#8a8a8a',
    yellow: '#c8c8c8',
    orange: '#5c5c5c',
    purple: '#3a3a3a',
    gray: '#9e9e9e',
    navy: '#2a2a2a',
    white: '#ffffff',
};

const baseEntity: EntityStyle = {
    bg: 'none',
    fg: '#1a1a1a',
    text: '#1a1a1a',
    border: 'solid',
    icon: 'none',
    shadow: 'none',
    font: 'sans',
    weight: 'normal',
    italic: false,
    textSize: 'md',
    padding: 'sm',
    spacing: 'sm',
    headerHeight: 'sm',
    cornerRadius: 'sm',
    bracket: 'none',
    capacityIcon: 'multiplier',
};

export const grayscaleTheme: Theme = {
    name: 'grayscale',
    surface: {
        page: '#f5f5f5',
        chart: '#ffffff',
        headerBox: '#ffffff',
    },
    entities: {
        roadmap: {
            ...baseEntity,
            headerHeight: 'md',
            padding: 'md',
        },
        swimlane: {
            ...baseEntity,
            fg: '#3a3a3a',
            text: '#3a3a3a',
            padding: 'sm',
            spacing: 'none',
            textSize: 'sm',
        },
        item: {
            ...baseEntity,
            bg: '#ffffff',
            fg: '#9e9e9e',
            text: '#1a1a1a',
            shadow: 'subtle',
            cornerRadius: 'sm',
        },
        parallel: {
            ...baseEntity,
            bracket: 'none',
            padding: 'xs',
        },
        group: {
            ...baseEntity,
            bracket: 'solid',
            padding: 'xs',
            fg: '#595959',
        },
        anchor: {
            ...baseEntity,
            bg: '#1a1a1a',
            fg: '#1a1a1a',
            text: '#1a1a1a',
            cornerRadius: 'sm',
        },
        milestone: {
            ...baseEntity,
            bg: '#2a2a2a',
            fg: '#2a2a2a',
            text: '#ffffff',
            border: 'solid',
        },
        footnote: {
            ...baseEntity,
            bg: 'none',
            fg: '#595959',
            text: '#595959',
            textSize: 'sm',
        },
        label: {
            ...baseEntity,
            bg: '#e8e8e8',
            fg: '#595959',
            text: '#595959',
            textSize: 'xs',
            padding: 'xs',
            cornerRadius: 'full',
        },
    },
    swimlane: {
        bandEven: '#ffffff',
        bandOdd: '#f5f5f5',
        separator: '#d4d4d4',
        frameTabText: '#3a3a3a',
        frameTabMuted: '#737373',
        border: '#d4d4d4',
        tabFill: '#e8e8e8',
        tabStroke: '#bdbdbd',
        tabText: '#3a3a3a',
        ownerText: '#737373',
        footnoteIndicator: '#4a4a4a',
        rowTintEven: '#ffffff',
        rowTintOdd: '#f5f5f5',
        utilizationOk: '#8a8a8a',
        utilizationWarn: '#595959',
        utilizationOver: '#1a1a1a',
    },
    timeline: {
        gridLine: '#bdbdbd',
        minorGridLine: '#d4d4d4',
        tickMark: '#bdbdbd',
        labelText: '#737373',
        panelFill: '#ffffff',
        border: '#d4d4d4',
    },
    header: {
        cardBorder: '#d4d4d4',
        author: '#737373',
    },
    item: {
        overflowX: '#1a1a1a',
        linkIconFg: '#1a1a1a',
        overflowTailFill: '#e8e8e8',
        overflowTailStroke: '#4a4a4a',
        overflowCaption: '#3a3a3a',
    },
    parallel: {
        bracketStroke: '#3a3a3a',
    },
    anchorDiamond: {
        fill: '#ffffff',
        stroke: '#3a3a3a',
        label: '#3a3a3a',
        cutLine: '#737373',
    },
    milestoneDiamond: {
        fill: '#1a1a1a',
        label: '#1a1a1a',
        cutLineNormal: '#2a2a2a',
        cutLineOverrun: '#4a4a4a',
        slack: '#1a1a1a',
    },
    footnotePanel: {
        fill: '#ffffff',
        border: '#d4d4d4',
        header: '#1a1a1a',
        title: '#1a1a1a',
        description: '#737373',
        number: '#4a4a4a',
    },
    nowline: {
        stroke: '#1a1a1a',
        labelText: '#ffffff',
        labelBg: '#1a1a1a',
    },
    milestone: {
        dashedInk: '#9e9e9e',
        overrun: '#4a4a4a',
    },
    anchor: {
        predecessorLine: '#9e9e9e',
    },
    dependency: {
        edgeStroke: '#595959',
        overflowStroke: '#1a1a1a',
    },
    footnote: {
        indicatorText: '#4a4a4a',
        descriptionMuted: '#737373',
    },
    includeRegion: {
        border: '#9e9e9e',
        label: '#3a3a3a',
        badge: '#737373',
        fill: '#f5f5f5',
        tabFill: '#ffffff',
        tabStroke: '#bdbdbd',
        tabText: '#1a1a1a',
        badgeFill: '#e8e8e8',
        badgeStroke: '#bdbdbd',
        badgeText: '#595959',
    },
    arrowhead: {
        neutral: '#595959',
        light: '#9e9e9e',
        dark: '#1a1a1a',
    },
    status: {
        done: '#8a8a8a',
        inProgress: '#595959',
        atRisk: '#737373',
        blocked: '#3a3a3a',
        planned: '#bdbdbd',
        neutral: '#bdbdbd',
    },
    statusDot: {
        onLight: {
            done: '#3a3a3a',
            inProgress: '#2a2a2a',
            atRisk: '#4a4a4a',
            blocked: '#1a1a1a',
            planned: '#595959',
            neutral: '#595959',
        },
        onDark: {
            done: '#d4d4d4',
            inProgress: '#e8e8e8',
            atRisk: '#c8c8c8',
            blocked: '#f0f0f0',
            planned: '#d4d4d4',
            neutral: '#d4d4d4',
        },
    },
    attribution: {
        mark: '#9e9e9e',
        link: '#1a1a1a',
    },
    diagnostic: {
        overlayBg: '#e8e8e8',
        errorText: '#1a1a1a',
    },
};
